package com.project.app.core.util;

public class MessageKeys {
    private MessageKeys() {
        throw new UnsupportedOperationException("This is a utility class and cannot be instantiated");
    }
    // General Error Messages
    public static final String UNAUTHORIZED = "unauthorized";  // Người dùng không có quyền truy cập
    public static final String FORBIDDEN = "forbidden";  // Truy cập bị
    public static final String USER_ROLE_IS_NOT_EXISTS = "user_role_is_not_exists";  // Role người dùng không tồn tại
    public static final String USER_INVALID = "user_invalid";  // Người dùng không hợp lệ
    public static final String USER_ME_DELETE = "user_me_delete";  // Người dùng không thể xóa chính mình
    public static final String USER_NOT_EXIST = "user_not_exist";  // Người dùng không tồn tại
    public static final String PASSWORD_INCORRECT = "password_incorrect";  // Mật khẩu không chính xác
    public static final String PASSWORDS_DO_NOT_MATCH = "passwords_do_not_match";  // Mật khẩu không khớp
    public static final String TOPIC_NOT_FOUND = "topic_not_found";  // Chủ đề không tìm thấy
    public static final String SOCIAL_OBJ_NOT_FOUND = "social_obj_not_found";  // Đối tượng xã hội không tìm thấy
    public static final String SOCIAL_SOURCE_NOT_FOUND = "social_source_not_found";  // Nguồn xã hội không tìm thấy
    public static final String GROUP_NOT_FOUND = "group_not_found";  // Nhóm không tìm thấy
    public static final String POST_NOT_FOUND = "post_not_found";  // Bài viết không tìm thấy
    public static final String LOT_NOT_FOUND = "lot_not_found";  // Lô hàng không tìm thấy
    public static final String WEBSITE_OBJ_NOT_FOUND = "website_obj_not_found";  // Đối tượng trang web không tìm thấy
    public static final String WEBSITE_SOURCE_NOT_FOUND = "website_source_not_found";  // Nguồn trang web không tìm thấy
    public static final String INTERNAL_SERVER_ERROR = "internal_server_error";  // Lỗi máy chủ nội bộ
    public static final String NOTE_LOCK = "note_lock";  // Ghi chú bị khóa
    public static final String LOT_REFERENCE_EXISTS = "lot_reference_exists";  // Tham chiếu lô hàng đã tồn tại
    public static final String GROUP_REFERENCE_EXISTS = "group_reference_exists";  // Tham chiếu nhóm đã tồn tại
    public static final String NOTIFICATION_CONFIG_NOT_FOUND = "notification_config_not_found";  // Cấu hình thông báo không tìm thấy
    public static final String NOTIFICATION_CONFIG_REFERENCE_EXISTS = "notification_config_reference_exists";  // Tham chiếu cấu hình thông báo đã tồn tại
    public static final String NOTIFICATION_NOT_FOUND = "notification_not_found";  // Thông báo không tìm thấy
    public static final String TIMES_TYPE_INCORRECT = "times_type_incorrect";  // Loại thời gian không chính xác
    public static final String SEND_TIME_INCORRECT = "send_time_incorrect";  // Thời gian gửi không chính xác
    public static final String SEND_DATE_EMPTY = "send_date_empty";  // Ngày gửi trống
    public static final String USER_GROUP_REFERENCE_EXISTS = "user_group_reference_exists";  // Tham chiếu nhóm người dùng đã tồn tại
    public static final String FULL_NAME_BLANK = "full_name_blank";  // Tên đầy đủ trống
    public static final String FULL_NAME_TYPE_INCORRECT = "full_name_type_incorrect";  // Kiểu tên đầy đủ không chính xác
    public static final String FULL_NAME_MAX_LENGTH = "full_name_max_length";  // Tên đầy đủ vượt quá độ dài tối đa
    public static final String FULL_NAME_MIN_LENGTH = "full_name_min_length";  // Tên đầy đủ dưới độ dài tối thiểu
    public static final String FULL_NAME_ALL_SPACE = "full_name_all_space";  // Tên đầy đủ chỉ chứa khoảng trắng
    public static final String PHONE_BLANK = "phone_blank";  // Số điện thoại trống
    public static final String PHONE_TYPE_INCORRECT = "phone_type_incorrect";  // Kiểu số điện thoại không chính xác
    public static final String PHONE_MAX_LENGTH = "phone_max_length";  // Số điện thoại vượt quá độ dài tối đa
    public static final String PHONE_MIN_LENGTH = "phone_min_length";  // Số điện thoại dưới độ dài tối thiểu
    public static final String PHONE_ALL_SPACE = "phone_all_space";  // Số điện thoại chỉ chứa khoảng trắng
    public static final String PHONE_REGEX = "phone_regex";  // Số điện thoại không hợp lệ theo định dạng
    public static final String PHONE_IS_EXIST = "phone_is_exist";  // Số điện thoại đã tồn tại
    public static final String EMAIL_BLANK = "email_blank";  // Địa chỉ email trống
    public static final String EMAIL_TYPE_INCORRECT = "email_type_incorrect";  // Kiểu địa chỉ email không chính xác
    public static final String EMAIL_MAX_LENGTH = "email_max_length";  // Địa chỉ email vượt quá độ dài tối đa
    public static final String EMAIL_MIN_LENGTH = "email_min_length";  // Địa chỉ email dưới độ dài tối thiểu
    public static final String EMAIL_ALL_SPACE = "email_all_space";  // Địa chỉ email chỉ chứa khoảng trắng
    public static final String EMAIL_REGEX = "email_regex";  // Địa chỉ email không hợp lệ theo định dạng
    public static final String EMAIL_IS_EXIST = "email_is_exist";  // Địa chỉ email đã tồn tại
    public static final String EMAIL_NOT_EXIST = "email_not_exist";  // Địa chỉ email không tồn tại
    public static final String EMAIL_IS_NOT_MATCH = "email_is_not_match"; // Địa chỉ mail không khớp
    public static final String USER_GROUP_BLANK = "user_group_blank";  // Nhóm người dùng trống
    public static final String USER_GROUP_IS_NOT_EXIST = "user_group_is_not_exist";  // Nhóm người dùng không tồn tại
    public static final String URL_BLANK = "url_blank";  // URL trống
    public static final String URL_TYPE_INCORRECT = "url_type_incorrect";  // Kiểu URL không chính xác
    public static final String URL_MAX_LENGTH = "url_max_length";  // URL vượt quá độ dài tối đa
    public static final String URL_MIN_LENGTH = "url_min_length";  // URL dưới độ dài tối thiểu
    public static final String URL_ALL_SPACE = "url_all_space";  // URL chỉ chứa khoảng trắng
    public static final String URL_REGEX = "url_regex";  // URL không hợp lệ theo định dạng
    public static final String URL_IS_EXIST = "url_is_exist";  // URL đã tồn tại
    public static final String NAME_BLANK = "name_blank";  // Tên trống
    public static final String NAME_TYPE_INCORRECT = "name_type_incorrect";  // Kiểu tên không chính xác
    public static final String NAME_MAX_LENGTH = "name_max_length";  // Tên vượt quá độ dài tối đa
    public static final String NAME_MIN_LENGTH = "name_min_length";  // Tên dưới độ dài tối thiểu
    public static final String NAME_ALL_SPACE = "name_all_space";  // Tên chỉ chứa khoảng trắng
    public static final String SOURCE_BLANK = "source_blank";  // Nguồn trống
    public static final String SOURCE_MAX_LENGTH = "source_max_length";  // Nguồn vượt quá độ dài tối đa
    public static final String SOURCE_MIN_LENGTH = "source_min_length";  // Nguồn dưới độ dài tối thiểu
    public static final String SOURCE_ALL_SPACE = "source_all_space";  // Nguồn chỉ chứa khoảng trắng
    public static final String SOURCE_REGEX = "source_regex";  // Nguồn không hợp lệ theo định dạng
    public static final String SOURCE_TYPE_BLANK = "source_type_blank";  // Kiểu nguồn trống
    public static final String SOURCE_TYPE_TYPE_INCORRECT = "source_type_type_incorrect";  // Kiểu nguồn không chính xác
    public static final String SOURCE_TYPE_MAX_LENGTH = "source_type_max_length";  // Kiểu nguồn vượt quá độ dài tối đa
    public static final String SOURCE_TYPE_MIN_LENGTH = "source_type_min_length";  // Kiểu nguồn dưới độ dài tối thiểu
    public static final String SOURCE_TYPE_ALL_SPACE = "source_type_all_space";  // Kiểu nguồn chỉ chứa khoảng trắng
    public static final String SOURCE_TYPE_REGEX = "source_type_regex";  // Kiểu nguồn không hợp lệ theo định dạng
    public static final String SOURCE_GROUP_REGEX = "source_group_regex";  // Nhóm nguồn không hợp lệ theo định dạng
    public static final String SOURCE_GROUP_IS_NOT_EXIST = "source_group_is_not_exist";  // Nhóm nguồn không tồn tại
    public static final String KEYWORD_BLANK = "keyword_blank"; // Lỗi khi từ khóa để trống
    public static final String KEYWORD_TYPE_INCORRECT = "keyword_type_incorrect"; // Lỗi khi kiểu của từ khóa không đúng
    public static final String KEYWORD_MAX_LENGTH = "keyword_max_length"; // Lỗi khi độ dài từ khóa vượt quá giới hạn tối đa
    public static final String KEYWORD_MIN_LENGTH = "keyword_min_length"; // Lỗi khi độ dài từ khóa ngắn hơn giới hạn tối thiểu
    public static final String KEYWORD_ALL_SPACE = "keyword_all_space"; // Lỗi khi từ khóa chỉ toàn khoảng trắng
    public static final String KEYWORD_REGEX = "keyword_regex"; // Lỗi khi từ khóa không khớp với biểu thức chính quy (regex)
    public static final String KEYWORD_NOT_FOUND = "keyword_not_found"; // Lỗi khi từ khóa không được tìm thấy
    public static final String KEYWORD_IS_EXIST = "keyword_is_exist"; // Lỗi khi từ khóa đã tồn tại
    public static final String SOURCE_CRAWL_IS_EXIST = "source_crawl_is_exist";
    public static final String SOURCE_CRAWL_IS_NOT_EXIST = "source_crawl_is_not_exist";
    public static final String DOMAIN_BLANK = "domain_blank";  // Tên miền trống
    public static final String DOMAIN_TYPE_INCORRECT = "domain_type_incorrect";  // Kiểu tên miền không chính xác
    public static final String DOMAIN_MAX_LENGTH = "domain_max_length";  // Tên miền vượt quá độ dài tối đa
    public static final String DOMAIN_MIN_LENGTH = "domain_min_length";  // Tên miền dưới độ dài tối thiểu
    public static final String DOMAIN_ALL_SPACE = "domain_all_space";  // Tên miền chỉ chứa khoảng trắng
    public static final String DOMAIN_REGEX = "domain_regex";  // Tên miền không hợp lệ theo định dạng
    public static final String DOMAIN_IS_EXIST = "domain_is_exist";  // Tên miền đã tồn tại
    public static final String DOMAIN_ALREADY_EXISTS = "domain_already_exists";  // Tên miền đã tồn tại trước đó
    public static final String START_URL_BLANK = "start_url_blank";  // URL bắt đầu trống
    public static final String START_URL_TYPE_INCORRECT = "start_url_type_incorrect";  // Kiểu URL bắt đầu không chính xác
    public static final String START_URL_MAX_LENGTH = "start_url_max_length";  // URL bắt đầu vượt quá độ dài tối đa
    public static final String START_URL_MIN_LENGTH = "start_url_min_length";  // URL bắt đầu dưới độ dài tối thiểu
    public static final String START_URL_ALL_SPACE = "start_url_all_space";  // URL bắt đầu chỉ chứa khoảng trắng
    public static final String START_URL_REGEX = "start_url_regex";  // URL bắt đầu không hợp lệ theo định dạng
    public static final String START_URL_IS_EXIST = "start_url_is_exist";  // URL bắt đầu đã tồn tại
    public static final String GROUP_ID_NOT_EXIST = "group_id_not_exist";  // ID nhóm không tồn tại
    public static final String ITEM_ID_NOT_EXIST = "item_id_not_exist";  // ID mục không tồn tại
    public static final String CURRENCY_IS_EXIST = "currency_is_exist";  // Tiền tệ đã tồn tại
    public static final String CURRENCY_IS_NOT_EXIST = "currency_is_not_exist";  // Tiền tệ không tồn tại
    public static final String CURRENCY_BLANK = "currency_blank";  // Tiền tệ trống
    public static final String CURRENCY_MAX_LENGTH = "currency_max_length";  // Tiền tệ vượt quá độ dài tối đa
    public static final String CURRENCY_MIN_LENGTH = "currency_min_length";  // Tiền tệ dưới độ dài tối thiểu
    public static final String CURRENCY_ALL_SPACE = "currency_all_space";  // Tiền tệ chỉ chứa khoảng trắng
    public static final String CURRENCY_TYPE_INCORRECT = "currency_type_incorrect";  // Kiểu tiền tệ không chính xác
    public static final String USER_DEACTIVE = "user_deactive";  // Người dùng đã bị vô hiệu hóa
    public static final String CURRENCY_REGEX = "currency_regex";  // Tiền tệ không hợp lệ theo định dạng
    public static final String USER_ACCOUNT_CREATE = "user_account_create";  // Tạo tài khoản người dùng
    public static final String USER_ACCOUNT_UPDATE = "user_account_update";  // Cập nhật tài khoản người dùng
    public static final String EMAIL_USER_IS_EXISTS = "email_user_is_exists"; // Email tài khoản đã tồn tại
    public static final String NAME_USER_IS_EXISTS = "name_user_is_exists"; // Tên tài khoản đã tồn tại
    public static final String FILE_SAVE_ERROR = "file_save_error";  // Có lỗi xảy ra khi cố lưu file
    public static final String FILE_IS_EXISTS = "file_is_exists"; // file đã tồn tại
    public static final String FILE_NOT_FOUND = "file_not_found"; // file không tồn tại
    public static final String POSTS_FILTER_ERROR = "posts_filter_error"; // có lỗi khi filter post
    public static final String POSTS_TRANS_INVALID = "posts_trans_invalid"; // đầu vào không hợp lệ
    public static final String POSTS_TRANS_UPDATE_ERROR = "posts_trans_update_error"; // có lỗi trong quá trình cập nhật trans post
    public static final String POSTS_TRANS_SPAM_INVALID = "posts_trans_spam_invalid";
    public static final String POSTS_TRANS_SENTIMENT_INVALID = "posts_trans_sentiment_invalid";
    public static final String POSTS_TRANS_COMPLETED_INVALID = "posts_trans_completed_invalid";
    public static final String POSTS_TRANS_TAG_INVALID = "posts_trans_tag_invalid";
    public static final String OPERATION_INFO_SAVE_ERROR = "operation_info_save_error";  // Có lỗi khi lưu thông tin người thao tác
    public static final String TAG_IS_EXIST = "tag_is_exist";
    public static final String TAG_NOT_FOUND = "tag_not_found";
    public static final String TAG_LEVEL_INVALID = "tag_level_invalid";
    public static final String REPORT_SAVE_ERROR = "report_save_error";
    public static final String SETTING_AUTO_SEND_REPORT_NOT_FOUND = "setting_auto_send_report_not_found";
}

