api:
  prefix: /api/v1

jwt:
  expiration: 604800
  expirationForgotPass: 1800
  secretKey: ${JWT_SECRET_KEY:TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=}
  secretKeyForgotPass: ${JWT_SECRET_KEY_FORGOT_PASS:f8CIClniZGjCgXh5kCRwdb9HMoG//Jlg+tfqSXIJU4k=}

logging:
  level:
    org:
      springframework:
        security: info

spring:
  devtools:
    restart:
      enabled: false

  data:
    redis:
      host: ${REDIS_HOST:103.97.125.64}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:tRuGz%3Dz_m*7-egJlfaEB}
      repositories:
        enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: 55
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: none

  mail:
    host: ${MAIL_HOST:pro34.emailse2342rver.vn}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:234@abp.vn}
    password: ${MAIL_PASSWORD:ABPde234vteam234@1235}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

scheduler:
  enabled: true
