package com.project.app.core.util;

public class MessageKeysConstant {
    private MessageKeysConstant() {
        throw new UnsupportedOperationException("This is a utility class and cannot be instantiated");
    }
    // General Error Messages
    public static final String UNAUTHORIZED = "UNAUTHORIZED";  // Người dùng không có quyền truy cập
    public static final String FORBIDDEN = "FORBIDDEN";  // Truy cập bị cấm
    public static final String USER_ROLE_IS_NOT_EXISTS = "USER_ROLE_IS_NOT_EXISTS";  // Role người dùng không tồn tại
    public static final String USER_INVALID = "USER_INVALID";  // Người dùng không hợp lệ
    public static final String USER_ME_DELETE = "USER_ME_DELETE";  // Người dùng không thể xóa chính mình
    public static final String USER_NOT_EXIST = "USER_NOT_EXIST";  // Người dùng không tồn tại
    public static final String PASSWORD_INCORRECT = "PASSWORD_INCORRECT";  // Mật khẩu không chính xác
    public static final String PASSWORDS_DO_NOT_MATCH = "PASSWORDS_DO_NOT_MATCH";  // Mật khẩu không khớp
    public static final String TOPIC_NOT_FOUND = "TOPIC_NOT_FOUND";  // Chủ đề không tìm thấy
    public static final String SOCIAL_OBJ_NOT_FOUND = "SOCIAL_OBJ_NOT_FOUND";  // Đối tượng xã hội không tìm thấy
    public static final String SOCIAL_SOURCE_NOT_FOUND = "SOCIAL_SOURCE_NOT_FOUND";  // Nguồn xã hội không tìm thấy
    public static final String GROUP_NOT_FOUND = "GROUP_NOT_FOUND";  // Nhóm không tìm thấy
    public static final String POST_NOT_FOUND = "POST_NOT_FOUND";  // Bài viết không tìm thấy
    public static final String LOT_NOT_FOUND = "LOT_NOT_FOUND";  // Lô hàng không tìm thấy
    public static final String WEBSITE_OBJ_NOT_FOUND = "WEBSITE_OBJ_NOT_FOUND";  // Đối tượng trang web không tìm thấy
    public static final String WEBSITE_SOURCE_NOT_FOUND = "WEBSITE_SOURCE_NOT_FOUND";  // Nguồn trang web không tìm thấy
    public static final String INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";  // Lỗi máy chủ nội bộ
    public static final String NOTE_LOCK = "NOTE_LOCK";  // Ghi chú bị khóa
    public static final String LOT_REFERENCE_EXISTS = "LOT_REFERENCE_EXISTS";  // Tham chiếu lô hàng đã tồn tại
    public static final String GROUP_REFERENCE_EXISTS = "GROUP_REFERENCE_EXISTS";  // Tham chiếu nhóm đã tồn tại
    public static final String NOTIFICATION_CONFIG_NOT_FOUND = "NOTIFICATION_CONFIG_NOT_FOUND";  // Cấu hình thông báo không tìm thấy
    public static final String NOTIFICATION_CONFIG_REFERENCE_EXISTS = "NOTIFICATION_CONFIG_REFERENCE_EXISTS";  // Tham chiếu cấu hình thông báo đã tồn tại
    public static final String NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND";  // Thông báo không tìm thấy
    public static final String TIMES_TYPE_INCORRECT = "TIMES_TYPE_INCORRECT";  // Loại thời gian không chính xác
    public static final String SEND_TIME_INCORRECT = "SEND_TIME_INCORRECT";  // Thời gian gửi không chính xác
    public static final String SEND_DATE_EMPTY = "SEND_DATE_EMPTY";  // Ngày gửi trống
    public static final String USER_GROUP_REFERENCE_EXISTS = "USER_GROUP_REFERENCE_EXISTS";  // Tham chiếu nhóm người dùng đã tồn tại
    public static final String FULL_NAME_BLANK = "FULL_NAME_BLANK";  // Tên đầy đủ trống
    public static final String FULL_NAME_TYPE_INCORRECT = "FULL_NAME_TYPE_INCORRECT";  // Kiểu tên đầy đủ không chính xác
    public static final String FULL_NAME_MAX_LENGTH = "FULL_NAME_MAX_LENGTH";  // Tên đầy đủ vượt quá độ dài tối đa
    public static final String FULL_NAME_MIN_LENGTH = "FULL_NAME_MIN_LENGTH";  // Tên đầy đủ dưới độ dài tối thiểu
    public static final String FULL_NAME_ALL_SPACE = "FULL_NAME_ALL_SPACE";  // Tên đầy đủ chỉ chứa khoảng trắng
    public static final String PHONE_BLANK = "PHONE_BLANK";  // Số điện thoại trống
    public static final String PHONE_TYPE_INCORRECT = "PHONE_TYPE_INCORRECT";  // Kiểu số điện thoại không chính xác
    public static final String PHONE_MAX_LENGTH = "PHONE_MAX_LENGTH";  // Số điện thoại vượt quá độ dài tối đa
    public static final String PHONE_MIN_LENGTH = "PHONE_MIN_LENGTH";  // Số điện thoại dưới độ dài tối thiểu
    public static final String PHONE_ALL_SPACE = "PHONE_ALL_SPACE";  // Số điện thoại chỉ chứa khoảng trắng
    public static final String PHONE_REGEX = "PHONE_REGEX";  // Số điện thoại không hợp lệ theo định dạng
    public static final String PHONE_IS_EXIST = "PHONE_IS_EXIST";  // Số điện thoại đã tồn tại
    public static final String EMAIL_BLANK = "EMAIL_BLANK";  // Địa chỉ email trống
    public static final String EMAIL_TYPE_INCORRECT = "EMAIL_TYPE_INCORRECT";  // Kiểu địa chỉ email không chính xác
    public static final String EMAIL_MAX_LENGTH = "EMAIL_MAX_LENGTH";  // Địa chỉ email vượt quá độ dài tối đa
    public static final String EMAIL_MIN_LENGTH = "EMAIL_MIN_LENGTH";  // Địa chỉ email dưới độ dài tối thiểu
    public static final String EMAIL_ALL_SPACE = "EMAIL_ALL_SPACE";  // Địa chỉ email chỉ chứa khoảng trắng
    public static final String EMAIL_REGEX = "EMAIL_REGEX";  // Địa chỉ email không hợp lệ theo định dạng
    public static final String EMAIL_IS_EXIST = "EMAIL_IS_EXIST";  // Địa chỉ email đã tồn tại
    public static final String USER_GROUP_BLANK = "USER_GROUP_BLANK";  // Nhóm người dùng trống
    public static final String USER_GROUP_IS_NOT_EXIST = "USER_GROUP_IS_NOT_EXIST";  // Nhóm người dùng không tồn tại
    public static final String URL_BLANK = "URL_BLANK";  // URL trống
    public static final String URL_TYPE_INCORRECT = "URL_TYPE_INCORRECT";  // Kiểu URL không chính xác
    public static final String URL_MAX_LENGTH = "URL_MAX_LENGTH";  // URL vượt quá độ dài tối đa
    public static final String URL_MIN_LENGTH = "URL_MIN_LENGTH";  // URL dưới độ dài tối thiểu
    public static final String URL_ALL_SPACE = "URL_ALL_SPACE";  // URL chỉ chứa khoảng trắng
    public static final String URL_REGEX = "URL_REGEX";  // URL không hợp lệ theo định dạng
    public static final String URL_IS_EXIST = "URL_IS_EXIST";  // URL đã tồn tại
    public static final String NAME_BLANK = "NAME_BLANK";  // Tên trống
    public static final String NAME_TYPE_INCORRECT = "NAME_TYPE_INCORRECT";  // Kiểu tên không chính xác
    public static final String NAME_MAX_LENGTH = "NAME_MAX_LENGTH";  // Tên vượt quá độ dài tối đa
    public static final String NAME_MIN_LENGTH = "NAME_MIN_LENGTH";  // Tên dưới độ dài tối thiểu
    public static final String NAME_ALL_SPACE = "NAME_ALL_SPACE";  // Tên chỉ chứa khoảng trắng
    public static final String SOURCE_BLANK = "SOURCE_BLANK";  // Nguồn trống
    public static final String SOURCE_MAX_LENGTH = "SOURCE_MAX_LENGTH";  // Nguồn vượt quá độ dài tối đa
    public static final String SOURCE_MIN_LENGTH = "SOURCE_MIN_LENGTH";  // Nguồn dưới độ dài tối thiểu
    public static final String SOURCE_ALL_SPACE = "SOURCE_ALL_SPACE";  // Nguồn chỉ chứa khoảng trắng
    public static final String SOURCE_REGEX = "SOURCE_REGEX";  // Nguồn không hợp lệ theo định dạng
    public static final String SOURCE_TYPE_BLANK = "SOURCE_TYPE_BLANK";  // Kiểu nguồn trống
    public static final String SOURCE_TYPE_TYPE_INCORRECT = "SOURCE_TYPE_TYPE_INCORRECT";  // Kiểu nguồn không chính xác
    public static final String SOURCE_TYPE_MAX_LENGTH = "SOURCE_TYPE_MAX_LENGTH";  // Kiểu nguồn vượt quá độ dài tối đa
    public static final String SOURCE_TYPE_MIN_LENGTH = "SOURCE_TYPE_MIN_LENGTH";  // Kiểu nguồn dưới độ dài tối thiểu
    public static final String SOURCE_TYPE_ALL_SPACE = "SOURCE_TYPE_ALL_SPACE";  // Kiểu nguồn chỉ chứa khoảng trắng
    public static final String SOURCE_TYPE_REGEX = "SOURCE_TYPE_REGEX";  // Kiểu nguồn không hợp lệ theo định dạng
    public static final String SOURCE_GROUP_REGEX = "SOURCE_GROUP_REGEX";  // Nhóm nguồn không hợp lệ theo định dạng
    public static final String SOURCE_GROUP_IS_NOT_EXIST = "SOURCE_GROUP_IS_NOT_EXIST";  // Nhóm nguồn không tồn tại
    public static final String DOMAIN_BLANK = "DOMAIN_BLANK";  // Tên miền trống
    public static final String DOMAIN_TYPE_INCORRECT = "DOMAIN_TYPE_INCORRECT";  // Kiểu tên miền không chính xác
    public static final String DOMAIN_MAX_LENGTH = "DOMAIN_MAX_LENGTH";  // Tên miền vượt quá độ dài tối đa
    public static final String DOMAIN_MIN_LENGTH = "DOMAIN_MIN_LENGTH";  // Tên miền dưới độ dài tối thiểu
    public static final String DOMAIN_ALL_SPACE = "DOMAIN_ALL_SPACE";  // Tên miền chỉ chứa khoảng trắng
    public static final String DOMAIN_REGEX = "DOMAIN_REGEX";  // Tên miền không hợp lệ theo định dạng
    public static final String DOMAIN_IS_EXIST = "DOMAIN_IS_EXIST";  // Tên miền đã tồn tại
    public static final String DOMAIN_ALREADY_EXISTS = "DOMAIN_ALREADY_EXISTS";  // Tên miền đã tồn tại trước đó
    public static final String START_URL_BLANK = "START_URL_BLANK";  // URL bắt đầu trống
    public static final String START_URL_TYPE_INCORRECT = "START_URL_TYPE_INCORRECT";  // Kiểu URL bắt đầu không chính xác
    public static final String START_URL_MAX_LENGTH = "START_URL_MAX_LENGTH";  // URL bắt đầu vượt quá độ dài tối đa
    public static final String START_URL_MIN_LENGTH = "START_URL_MIN_LENGTH";  // URL bắt đầu dưới độ dài tối thiểu
    public static final String START_URL_ALL_SPACE = "START_URL_ALL_SPACE";  // URL bắt đầu chỉ chứa khoảng trắng
    public static final String START_URL_REGEX = "START_URL_REGEX";  // URL bắt đầu không hợp lệ theo định dạng
    public static final String START_URL_IS_EXIST = "START_URL_IS_EXIST";  // URL bắt đầu đã tồn tại
    public static final String GROUP_ID_NOT_EXIST = "GROUP_ID_NOT_EXIST";  // ID nhóm không tồn tại
    public static final String ITEM_ID_NOT_EXIST = "ITEM_ID_NOT_EXIST";  // ID mục không tồn tại
    public static final String CURRENCY_IS_EXIST = "CURRENCY_IS_EXIST";  // Tiền tệ đã tồn tại
    public static final String CURRENCY_IS_NOT_EXIST = "CURRENCY_IS_NOT_EXIST";  // Tiền tệ không tồn tại
    public static final String CURRENCY_BLANK = "CURRENCY_BLANK";  // Tiền tệ trống
    public static final String CURRENCY_MAX_LENGTH = "CURRENCY_MAX_LENGTH";  // Tiền tệ vượt quá độ dài tối đa
    public static final String CURRENCY_MIN_LENGTH = "CURRENCY_MIN_LENGTH";  // Tiền tệ dưới độ dài tối thiểu
    public static final String CURRENCY_ALL_SPACE = "CURRENCY_ALL_SPACE";  // Tiền tệ chỉ chứa khoảng trắng
    public static final String CURRENCY_TYPE_INCORRECT = "CURRENCY_TYPE_INCORRECT";  // Kiểu tiền tệ không chính xác
    public static final String USER_DEACTIVE = "USER_DEACTIVE";  // Người dùng đã bị vô hiệu hóa
    public static final String CURRENCY_REGEX = "CURRENCY_REGEX";  // Tiền tệ không hợp lệ theo định dạng
    public static final String USER_ACCOUNT_CREATE = "USER_ACCOUNT_CREATE";  // Tạo tài khoản người dùng
    public static final String USER_ACCOUNT_UPDATE = "USER_ACCOUNT_UPDATE";  // Cập nhật tài khoản người dùng
    public static final String EMAIL_USER_IS_EXISTS = "EMAIL_USER_IS_EXISTS";  // Email tài khoản đã tồn tại
    public static final String NAME_USER_IS_EXISTS = "NAME_USER_IS_EXISTS";  // Tên tài khoản đã tồn tại

}
